name: Build and deploy store

on:
  push:
    branches: [ front-end-release ]

  # Run workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Install dependencies
        run: npm ci
        working-directory: Front-end/store
      - name: Build dependencies
        run: npm run build
        working-directory: Front-end/store
      - name: Archive production artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: Front-end/store/dist/store
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: Front-end/store/dist/store
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_PATH: Front-end/store
